# Generated by Django 2.2.3 on 2019-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0002_auto_20190722_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
