# Generated by Django 2.2.3 on 2019-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0003_auto_20190722_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
